version: '2.4'

services:
  ldap:
    extends:
      file: docker-compose.base.yml
      service: ldap
    volumes:
      - ./tests/testLoad/limitNumberOfResults.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/03-limitNumberOfResults.ldif

  sut:
    container_name: ldap-test-runner
    image: ubuntu:latest
    volumes:
      - ./tests/base/groups.ldif:/groups.ldif:ro
      - ./tests/startup.sh:/startup.sh
      - ./tests/installBase.sh:/installBase.sh
      - ./tests/names.txt:/names.txt:ro
      - ./tests/surnames.txt:/surnames.txt:ro
      - ./tests/generateUserLdif.sh:/generateUserLdif.sh:ro
      - ./tests/generateUsersInGroupLdif.sh:/generateUsersInGroupLdif.sh:ro
      - ./tests/testLoad/test.sh:/test.sh
      - ./tests/testLoad/roles.ldif:/roles.ldif
      - ./tests/testLoad/users-in-groups.ldif:/users-in-groups.ldif
    entrypoint: /startup.sh
    depends_on: 
        - ldap
